import 'package:share_plus/share_plus.dart';
import 'package:flutter/services.dart';
import '../models/heartbeat_data.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'dart:io';
import 'package:path_provider/path_provider.dart';

class ECGSharingService {
  /// Share ECG data as text
  Future<void> shareECGAsText(HeartbeatData data) async {
    try {
      final text = '''
IntelIWave - Heart Rate Report

Heart Rate: ${data.heartRate} BPM
Status: ${data.status}
Time: ${data.timestamp.toString()}
Device: ${data.deviceId}

This data was recorded using IntelIWave heart rate monitoring app.
''';

      await Share.share(
        text,
        subject: 'Heart Rate Data from IntelIWave',
      );
    } catch (e) {
      throw Exception('Failed to share ECG data: $e');
    }
  }

  /// Share multiple ECG records as text
  Future<void> shareMultipleECG(List<HeartbeatData> dataList) async {
    try {
      final buffer = StringBuffer();
      buffer.writeln('IntelIWave - Heart Rate Report');
      buffer.writeln('=' * 50);
      buffer.writeln('');

      for (final data in dataList) {
        buffer.writeln('Heart Rate: ${data.heartRate} BPM');
        buffer.writeln('Status: ${data.status}');
        buffer.writeln('Time: ${data.timestamp.toString()}');
        buffer.writeln('Device: ${data.deviceId}');
        buffer.writeln('-' * 50);
      }

      buffer.writeln('');
      buffer.writeln('Generated by IntelIWave Heart Rate Monitoring App');

      await Share.share(
        buffer.toString(),
        subject: 'Heart Rate Records from IntelIWave',
      );
    } catch (e) {
      throw Exception('Failed to share ECG records: $e');
    }
  }

  /// Generate and share ECG as PDF
  Future<void> shareECGAsPDF(HeartbeatData data, String userName) async {
    try {
      final pdf = pw.Document();

      // Load logo image
      final logoData = await rootBundle.load('assets/images/app_logo.png');
      final logoImage = pw.MemoryImage(logoData.buffer.asUint8List());

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.center,
                  children: [
                    pw.Image(logoImage, width: 32, height: 32),
                    pw.SizedBox(width: 8),
                    pw.Text(
                      'IntelIWave Heart Rate Report',
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 20),
                pw.Text(
                  'Patient Information',
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Text('Name: $userName'),
                pw.Text('Report Date: ${DateTime.now().toString().split('.')[0]}'),
                pw.SizedBox(height: 20),
                pw.Text(
                  'Heart Rate Metrics',
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Text('Heart Rate: ${data.heartRate} BPM'),
                pw.Text('Status: ${data.status}'),
                pw.Text('Recording Time: ${data.timestamp.toString()}'),
                pw.Text('Device ID: ${data.deviceId}'),
                pw.SizedBox(height: 20),
                if (data.ecgData.isNotEmpty) ...[
                  pw.Text(
                    'ECG Waveform',
                    style: pw.TextStyle(
                      fontSize: 16,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 8),
                  () {
                    final rawSamples = data.ecgData.map((e) => e.toDouble()).toList();
                    final sum = rawSamples.reduce((a, b) => a + b);
                    final mean = sum / rawSamples.length;
                    final samples = rawSamples.map((v) => v - mean).toList();

                    double maxAbs = 200.0;
                    for (final v in samples) {
                      final a = v.abs();
                      if (a > maxAbs) maxAbs = a;
                    }
                    maxAbs *= 1.15;
                    final minY = -maxAbs;
                    final maxY = maxAbs;

                    double normalizeForPdf(double val) {
                      final norm = ((val - minY) / (maxY - minY)).clamp(0.0, 1.0);
                      return norm * 100.0;
                    }

                    return pw.Container(
                      height: 100,
                      width: 530,
                      decoration: pw.BoxDecoration(
                        color: PdfColors.white,
                        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                        border: pw.Border.all(
                          color: PdfColor.fromInt(0xFFEF9A9A),
                          width: 0.8,
                        ),
                      ),
                      child: pw.CustomPaint(
                        size: const PdfPoint(530, 100),
                        painter: (PdfGraphics canvas, PdfPoint sz) {
                          // Minor red grid (1 mm = 1 small square = 0.04s)
                          final smallPx = 1.0 * PdfPageFormat.mm;
                          canvas.setStrokeColor(PdfColor.fromInt(0xFFFFCDD2));
                          canvas.setLineWidth(0.35);
                          for (double x = 0; x <= sz.x; x += smallPx) {
                            canvas.moveTo(x, 0);
                            canvas.lineTo(x, sz.y);
                            canvas.strokePath();
                          }
                          for (double y = 0; y <= sz.y; y += smallPx) {
                            canvas.moveTo(0, y);
                            canvas.lineTo(sz.x, y);
                            canvas.strokePath();
                          }

                          // Major red grid (5 mm = 1 large square = 0.20s)
                          final bigPx = 5.0 * PdfPageFormat.mm;
                          canvas.setStrokeColor(PdfColor.fromInt(0xFFEF9A9A));
                          canvas.setLineWidth(0.75);
                          for (double x = 0; x <= sz.x; x += bigPx) {
                            canvas.moveTo(x, 0);
                            canvas.lineTo(x, sz.y);
                            canvas.strokePath();
                          }
                          for (double y = 0; y <= sz.y; y += bigPx) {
                            canvas.moveTo(0, y);
                            canvas.lineTo(sz.x, y);
                            canvas.strokePath();
                          }

                          // Baseline Y=0
                          final baselineY = normalizeForPdf(0);
                          canvas.setStrokeColor(PdfColor.fromInt(0xFFE57373));
                          canvas.setLineWidth(0.9);
                          canvas.moveTo(0, baselineY);
                          canvas.lineTo(sz.x, baselineY);
                          canvas.strokePath();

                          // ECG waveform line (Dark Crimson Red)
                          if (samples.isNotEmpty) {
                            canvas.setStrokeColor(PdfColor.fromInt(0xFFB71C1C));
                            canvas.setLineWidth(1.3);
                            final step = (25.0 * PdfPageFormat.mm) / 250.0;
                            canvas.moveTo(0, normalizeForPdf(samples[0]));
                            for (int i = 1; i < samples.length; i++) {
                              canvas.lineTo(i * step, normalizeForPdf(samples[i]));
                            }
                            canvas.strokePath();
                          }
                        },
                      ),
                    );
                  }(),
                  pw.SizedBox(height: 15),
                ],
                pw.Divider(),
                pw.SizedBox(height: 20),
                pw.Text(
                  'Notes:',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(
                  'This heart rate report was generated by the IntelIWave application. '
                  'For medical concerns, please consult with a healthcare professional.',
                  textAlign: pw.TextAlign.justify,
                ),
              ],
            );
          },
        ),
      );

      final tempDir = await getTemporaryDirectory();
      final file = File('${tempDir.path}/ecg_report_${DateTime.now().millisecondsSinceEpoch}.pdf');
      await file.writeAsBytes(await pdf.save());

      await Share.shareXFiles(
        [XFile(file.path)],
        subject: 'Heart Rate Report from IntelIWave',
      );
    } catch (e) {
      throw Exception('Failed to generate PDF: $e');
    }
  }

  /// Export ECG data as CSV
  Future<String> exportECGAsCSV(List<HeartbeatData> dataList) async {
    try {
      final buffer = StringBuffer();
      
      // Header
      buffer.writeln('HeartRate,Status,Timestamp,DeviceID');
      
      // Data rows
      for (final data in dataList) {
        buffer.writeln(
          '${data.heartRate},${data.status},${data.timestamp},${data.deviceId}',
        );
      }

      return buffer.toString();
    } catch (e) {
      throw Exception('Failed to export CSV: $e');
    }
  }
}
