import 'package:share_plus/share_plus.dart';
import '../models/heartbeat_data.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'dart:io';
import 'package:path_provider/path_provider.dart';

class ECGSharingService {
  /// Share ECG data as text
  Future<void> shareECGAsText(HeartbeatData data) async {
    try {
      final text = '''
IntelIWave - Heart Rate Report

Heart Rate: ${data.heartRate} BPM
Status: ${data.status}
Time: ${data.timestamp.toString()}
Device: ${data.deviceId}

This data was recorded using IntelIWave heart rate monitoring app.
''';

      await Share.share(
        text,
        subject: 'Heart Rate Data from IntelIWave',
      );
    } catch (e) {
      throw Exception('Failed to share ECG data: $e');
    }
  }

  /// Share multiple ECG records as text
  Future<void> shareMultipleECG(List<HeartbeatData> dataList) async {
    try {
      final buffer = StringBuffer();
      buffer.writeln('IntelIWave - Heart Rate Report');
      buffer.writeln('=' * 50);
      buffer.writeln('');

      for (final data in dataList) {
        buffer.writeln('Heart Rate: ${data.heartRate} BPM');
        buffer.writeln('Status: ${data.status}');
        buffer.writeln('Time: ${data.timestamp.toString()}');
        buffer.writeln('Device: ${data.deviceId}');
        buffer.writeln('-' * 50);
      }

      buffer.writeln('');
      buffer.writeln('Generated by IntelIWave Heart Rate Monitoring App');

      await Share.share(
        buffer.toString(),
        subject: 'Heart Rate Records from IntelIWave',
      );
    } catch (e) {
      throw Exception('Failed to share ECG records: $e');
    }
  }

  /// Generate and share ECG as PDF
  Future<void> shareECGAsPDF(HeartbeatData data, String userName) async {
    try {
      final pdf = pw.Document();

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'IntelIWave Heart Rate Report',
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 20),
                pw.Text(
                  'Patient Information',
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Text('Name: $userName'),
                pw.Text('Report Date: ${DateTime.now().toString().split('.')[0]}'),
                pw.SizedBox(height: 20),
                pw.Text(
                  'Heart Rate Metrics',
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Text('Heart Rate: ${data.heartRate} BPM'),
                pw.Text('Status: ${data.status}'),
                pw.Text('Recording Time: ${data.timestamp.toString()}'),
                pw.Text('Device ID: ${data.deviceId}'),
                pw.SizedBox(height: 20),
                pw.Divider(),
                pw.SizedBox(height: 20),
                pw.Text(
                  'Notes:',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(
                  'This heart rate report was generated by the IntelIWave application. '
                  'For medical concerns, please consult with a healthcare professional.',
                  textAlign: pw.TextAlign.justify,
                ),
              ],
            );
          },
        ),
      );

      final tempDir = await getTemporaryDirectory();
      final file = File('${tempDir.path}/ecg_report_${DateTime.now().millisecondsSinceEpoch}.pdf');
      await file.writeAsBytes(await pdf.save());

      await Share.shareXFiles(
        [XFile(file.path)],
        subject: 'Heart Rate Report from IntelIWave',
      );
    } catch (e) {
      throw Exception('Failed to generate PDF: $e');
    }
  }

  /// Export ECG data as CSV
  Future<String> exportECGAsCSV(List<HeartbeatData> dataList) async {
    try {
      final buffer = StringBuffer();
      
      // Header
      buffer.writeln('HeartRate,Status,Timestamp,DeviceID');
      
      // Data rows
      for (final data in dataList) {
        buffer.writeln(
          '${data.heartRate},${data.status},${data.timestamp},${data.deviceId}',
        );
      }

      return buffer.toString();
    } catch (e) {
      throw Exception('Failed to export CSV: $e');
    }
  }
}
